Run all WebUI CI checks regardless of failure
This fixes an annoyance I've hit with the WebUI CI checks. If the linter fails, the GH Action immediately exits before the formatter has run. This can mean fixing the lint error and pushing up a change, only for the GH Action to then fail due to the formatter check.

This PR makes it so that all checks always run, with the job still failing if any of the checks failed. It should allow for a quicker feedback loop.

diff --git a/.github/workflows/ci_webui.yaml b/.github/workflows/ci_webui.yaml
--- a/.github/workflows/ci_webui.yaml
+++ b/.github/workflows/ci_webui.yaml
@@ -42,9 +42,13 @@ jobs:
         run: npm test
 
       - name: Lint code
+        id: lint
+        continue-on-error: true
         run: npm run lint
 
       - name: Format code
+        id: format
+        continue-on-error: true
         run: |
           npm run format
           git diff --exit-code
@@ -56,4 +60,26 @@ jobs:
           languages: javascript
 
       - name: Run CodeQL analysis
+        id: codeql
+        continue-on-error: true
         uses: github/codeql-action/analyze@v3
+
+      - name: Check for failures
+        if: always()
+        run: |
+          if [[ "${{ steps.lint.outcome }}" != "success" ]]; then
+            echo "Linting failed"
+            exit_code=1
+          fi
+
+          if [[ "${{ steps.format.outcome }}" != "success" ]]; then
+            echo "Code formatting check failed"
+            exit_code=1
+          fi
+
+          if [[ "${{ steps.codeql.outcome }}" != "success" ]]; then
+            echo "CodeQL analysis failed"
+            exit_code=1
+          fi
+
+          exit ${exit_code:-0}
